CREATE DATABASE Assetly;
USE Assetly;

-- Existing tables
CREATE TABLE USER_STOCKS (
    STOCK_ID VARCHAR(5) PRIMARY KEY,
    STOCK_NAME VARCHAR(50),
    QUANTITY INT,
    PRICE DECIMAL(10,2),
    SECTOR VARCHAR(50),
    PURCHASE_DATE DATE,
    AMOUNT DECIMAL(10,2)
);

CREATE TABLE USER_GOLD (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PRICE DECIMAL(10,2),
    WEIGHT DECIMAL(10,3),
    PURCHASE_DATE DATE,
    AMOUNT DECIMAL(10,2)
);

-- Additional tables for enhanced features
CREATE TABLE USER_PROFILE (
    USER_ID INT PRIMARY KEY AUTO_INCREMENT,
    NAME VARCHAR(50),
    EMAIL VARCHAR(50),
    PAN_NUMBER VARCHAR(10),
    DATE_OF_BIRTH DATE,
    MONTHLY_EXPENSE_LIMIT DECIMAL(10,2),
    CURRENT_EXPENSE DECIMAL(10,2) DEFAULT 0
);

CREATE TABLE TRANSACTION_HISTORY (
    TRANSACTION_ID INT AUTO_INCREMENT PRIMARY KEY,
    USER_ID INT DEFAULT 1,
    INVESTMENT_TYPE VARCHAR(10),
    ACTION VARCHAR(10),
    INVESTMENT_NAME VARCHAR(100),
    AMOUNT DECIMAL(10,2),
    TRANSACTION_DATE DATE
);

-- Insert sample profile data
INSERT INTO USER_PROFILE (NAME, EMAIL, PAN_NUMBER, DATE_OF_BIRTH, MONTHLY_EXPENSE_LIMIT) 
VALUES ('John Doe', 'john@email.com', 'ABCDE1234F', '1990-01-15', 5000.00);
